name: Smartsapp
description: SmartApp - Cross-Platform Messenger

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.0
    provider: ^4.3.2+3
    firebase_auth: ^0.18.4+1
    firebase_core: ^0.5.3
    firebase_storage: ^5.2.0
    cloud_firestore: ^0.14.4
    google_sign_in: ^4.5.6
    font_awesome_flutter: ^8.11.0
    http: ^0.12.2
    image_cropper: ^1.3.1
    image_picker: ^0.6.7+17
    shared_preferences: ^0.5.12+4
    uuid: ^2.2.2
    photo_view: ^0.10.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: ^0.8.1

flutter_icons:
    android: true
    ios: true
    image_path: "assets/img/icon.png"
    adaptive_icon_foreground: "assets/img/icon.png"

flutter:
    uses-material-design: true
    fonts:
        - family: Lato
          fonts:
              - asset: assets/fonts/Lato-Regular.ttf
              - asset: assets/fonts/Lato-Thin.ttf
                weight: 100
              - asset: assets/fonts/Lato-Light.ttf
                weight: 300
              - asset: assets/fonts/Lato-Bold.ttf
                weight: 700
              - asset: assets/fonts/Lato-Black.ttf
                weight: 900
    assets:
        - assets/img/chat_full.png
        - assets/img/icon.png
        - assets/img/loading.gif
