name: smartsapp
description: SmartApp - Cross-Platform Messenger

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    fonts:
        - family: Lato
          fonts:
              - asset: assets/fonts/Lato-Regular.ttf
              - asset: assets/fonts/Lato-Thin.ttf
                weight: 100
              - asset: assets/fonts/Lato-Light.ttf
                weight: 300
              - asset: assets/fonts/Lato-Bold.ttf
                weight: 700
              - asset: assets/fonts/Lato-Black.ttf
                weight: 900
    assets:
        - assets/img/chat.png
        - assets/img/chat_full.png
